Repository Allegheny-Ethical-CS/GatorMiner, pull requests merged in 2021-03, with the labels that each got.

#42 Add Contributing Guideline
  CONTRIBUTING.md
  README.md
Labels: documentation

#39 Add pylint to Pipfile and Github Action
  .github/workflows/main.yml
  .pylintrc
  CONTRIBUTING.md
  LICENSE
  Pipfile
  Pipfile.lock
  README.md
  src/constants.py
  src/doc_similarity.py
  src/get_handler.py
  src/json_util.py
  src/markdown.py
  src/summarizer.py
  src/topic_modeling.py
  src/visualization.py
  streamlit_web.py
  tests/test_analyzer.py
  tests/test_json_util.py
  tests/test_markdown.py
  tests/test_summarizer.py
Labels: enhancement

#44 Fix charmap error by encoding with utf8
  src/markdown.py
Labels: bug

#61 Fix #40 : images not appearing on the streamlit home page
  README.md
  streamlit_web.py
Labels: Team 3, bug
