Repository Allegheny-Ethical-CS/GatorMiner, pull requests merged in 2021-04, with the labels that each got.

#73 Change the Streamlit Version in Pipfile to 0.78.0
  Pipfile
Labels: bug

#76 Improve Streamlit landing page
  .travis.yml
  docs/LANDING_PAGE.md
  streamlit_web.py
Labels: Team 3, documentation

#62 Add Streamlit File Uploader as an Input Option
  src/markdown.py
  streamlit_web.py
  tests/test_markdown.py
Labels: question

#83 Display documents with Named Entity Recognition
  Pipfile.lock
  streamlit_web.py
Labels: high priority
